/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kotlin_repro;

import kotlin_repro.JavaConsumptionOnly.foo;

public class App {
    public static void main(String[] args) {
        System.out.println(foo.GetName());
        System.out.println(KotlinFileKt.ConsumeJavaFromKotlin());
    }
}
